name: Build And Push Pro-files Client Docker Image To Docker Hub

on:
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest version tag from Docker Hub
        id: get_version
        env:
          DOCKERHUB_USERNAME: ${{ secrets.PROFILES_DEV_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.PROFILES_DEV_HUB_SECRET }}
        run: |
          IMAGE_NAME="pro-files-client"
          REPO="$DOCKERHUB_USERNAME/$IMAGE_NAME"

          echo "Fetching tags for $REPO..."

          TAGS=$(curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD" \
            "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=10000" \
            | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+$' || echo "")

          MAX_VERSION=$(echo "$TAGS" | sed 's/v//' | sort -V | tail -n 1)

          if [[ -z "$MAX_VERSION" ]]; then
            NEXT_VERSION="1.0"
          else
            MAJOR=$(echo "$MAX_VERSION" | cut -d. -f1)
            MINOR=$(echo "$MAX_VERSION" | cut -d. -f2)

            if [[ "$MINOR" -ge 9 ]]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
            else
              MINOR=$((MINOR + 1))
            fi

            NEXT_VERSION="$MAJOR.$MINOR"
          fi

          echo "Next version: v$NEXT_VERSION"
          echo "VERSION=v$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROFILES_DEV_USERNAME }}
          password: ${{ secrets.PROFILES_DEV_HUB_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.PROFILES_DEV_USERNAME }}/pro-files-client:live
            ${{ secrets.PROFILES_DEV_USERNAME }}/pro-files-client:${{ steps.get_version.outputs.VERSION }}