name: Build And Push Pro-files Client Docker Image To Docker Hub

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest version tag from Docker Hub
        id: get_version
        env:
          DOCKERHUB_USERNAME: ${{ secrets.PROFILES_PROD_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.PROFILES_PROD_HUB_SECRET }}
        run: |
          IMAGE_NAME="pro-files-client"
          REPO="$DOCKERHUB_USERNAME/$IMAGE_NAME"

          echo "Fetching tags for $REPO..."

          TAGS=$(curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD" \
            "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" \
            | jq -r '.results[].name' | grep '^live-[0-9]*$' || echo "")

          MAX_VERSION=$(echo "$TAGS" | sed 's/live-//' | sort -n | tail -n 1)
          if [[ -z "$MAX_VERSION" ]]; then
            NEXT_VERSION=1
          else
            NEXT_VERSION=$((MAX_VERSION + 1))
          fi

          echo "Next version: v$NEXT_VERSION"
          echo "VERSION=v$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROFILES_PROD_USERNAME }}
          password: ${{ secrets.PROFILES_PROD_HUB_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.PROFILES_PROD_USERNAME }}/pro-files-client:live
            ${{ secrets.PROFILES_PROD_USERNAME }}/pro-files-client:${{ steps.get_version.outputs.VERSION }}